### ISSUE TITLE
[Tip] a simple Glance interface

### ISSUE THREAD

**Issue by vespadj** [gytisgreitai/zehnder-can-mqtt#3]
I would like to share a simple glance type interface for custom lovelace without custom card.
For a quick check, or for lazy to search and to adapt a custom card.

Change ventilation level on first 4 buttons.
```yaml
type: glance
title: Comfoair
columns: 4
entities:
  - entity: sensor.comfoair_ventilation_level
    name: '0'
    icon: mdi:fan-off
    tap_action:
      action: call-service
      service: mqtt.publish
      service_data:
        topic: comfoair/action
        payload: ventilation_level_0
  - entity: sensor.comfoair_ventilation_level
    name: '1'
    icon: mdi:fan-speed-1
    show_last_changed: true
    tap_action:
      action: call-service
      service: mqtt.publish
      service_data:
        topic: comfoair/action
        payload: ventilation_level_1
  - entity: sensor.comfoair_operating_mode
    name: '2'
    icon: mdi:fan-speed-2
    tap_action:
      action: call-service
      service: mqtt.publish
      service_data:
        topic: comfoair/action
        payload: ventilation_level_2
  - entity: sensor.comfoair_operating_mode
    name: '3'
    icon: mdi:fan-speed-3
    show_last_changed: true
    tap_action:
      action: call-service
      service: mqtt.publish
      service_data:
        topic: comfoair/action
        payload: ventilation_level_3
  - entity: sensor.comfoair_air_outdoor_temperature
    name: Outdoor
  - entity: sensor.comfoair_air_outdoor_humidity
    name: ''
  - entity: sensor.comfoair_air_supply_temperature
    name: Supply
  - entity: sensor.comfoair_air_supply_humidity
    name: ''
  - entity: sensor.comfoair_air_extract_temperature
    name: Extract
  - entity: sensor.comfoair_air_extract_humidity
    name: ''
  - entity: sensor.comfoair_bypass_open_percentage
    name: By-pass
    icon: mdi:math-norm-box
  - entity: sensor.comfoair_target_temperature
    name: Target
```
